#!/usr/bin/env python3
"""
AgentMint Quickstart — generated by `agentmint init`

Run this to see your first signed receipt:
    python3 quickstart.py

What it does:
    1. Creates a Notary (generates an Ed25519 keypair)
    2. Creates a plan with scopes from your scan results
    3. Notarises a simulated tool call
    4. Verifies the receipt signature
    5. Exports an evidence package you can hand to an auditor
"""
from pathlib import Path
from agentmint.notary import Notary

notary = Notary()

# Plan — scopes match your actual tool calls from the scan
plan = notary.create_plan(
    user="developer@yourcompany.com",
    action="agent-ops",
    scope=['hook:before_tool_call', 'tool:S3Reader', 'tool:S3ReaderTool', 'tool:S3Tool', 'tool:agentmint_audit', 'tool:agentmint_authorize', 'tool:agentmint_issue_plan', 'tool:create_plan', 'tool:fetch_ca_certs', 'tool:get_flight_status', 'tool:get_receipt', 'tool:get_registry', 'tool:get_weather', 'tool:lookup_account', 'tool:lookup_booking', 'tool:read_file', 'tool:s3_tool', 'tool:search_web', 'tool:send_email', 'tool:send_notification', 'tool:write_file', 'tool:write_json', 'tool:write_text'],
    delegates_to=["agent"],
)

# Simulate a tool call — replace with your real tool
receipt = notary.notarise(
    action="tool:send_notification",
    agent="agent",
    plan=plan,
    evidence={
        "tool": "send_notification",
        "file": "examples/openai_agents_receipts_demo/demo_open_ai_receipts.py",
        "simulated": True,
    },
)

# Verify
assert notary.verify_receipt(receipt), "Receipt verification failed!"

print(f"""
✓ Receipt {receipt.short_id} — signed and verified

  action:    tool:send_notification
  agent:     agent
  in_policy: {receipt.in_policy}
  signature: {receipt.signature[:40]}...

Next steps:
  1. Add notary.notarise() calls to your real tools (see agentmint init output)
  2. Run `agentmint verify .` in CI to enforce coverage
  3. Export evidence: notary.export_evidence(Path("./evidence"))
""")

# Export evidence package
evidence_dir = Path("./agentmint-evidence")
evidence_dir.mkdir(exist_ok=True)
notary.export_evidence(evidence_dir)
print(f"✓ Evidence exported to {evidence_dir}/")
print(f"  Verify independently: cd {evidence_dir} && bash verify.sh")
