"""
patcher.py — YAML generation + codemod patches.

Design principle: the generated yaml contains only provable facts
from the scan. It is never wrong — it may be incomplete (the developer
tightens scopes for production), but it is never incorrect.

Generates:
  - agentmint.yaml with audit-mode defaults (facts only)
  - Import injection (from agentmint.notary import Notary)
  - Per-tool patch instructions matching real SDK patterns
  - quickstart.py — runnable script that produces first receipt
"""
from __future__ import annotations

from collections import defaultdict
from typing import List

import yaml
import libcst as cst

from .candidates import ToolCandidate


# ═══════════════════════════════════════════════════════════════
# YAML generation — facts only
# ═══════════════════════════════════════════════════════════════

def generate_yaml(candidates: List[ToolCandidate]) -> str:
    """Generate agentmint.yaml from scan results.

    Every field is a proven fact or a safe default:
      - scope: tool:<exact_name> — matches what notarise() expects
      - mode: audit — logs everything, blocks nothing
      - framework/file/line: from the scan, verifiable
      - no rate limit guesses — defaults handle it
    """
    tools = {}
    for c in candidates:
        if c.symbol.startswith("<"):
            continue
        # Deduplicate: keep definition over registration, first wins
        if c.symbol in tools:
            continue
        tools[c.symbol] = {
            "scope": c.scope_suggestion,
            "framework": c.framework,
            "file": c.file,
            "line": c.line,
            "boundary": c.boundary,
        }

    config = {
        "version": 1,
        "mode": "audit",
        "defaults": {
            "shield": {"enabled": True, "mode": "audit"},
            "circuit_breaker": {"max_calls": 100, "window_seconds": 60},
            "signing": {"enabled": False},
        },
        "notary": {
            "enabled": True,
            "export_path": "./agentmint-evidence",
        },
        "tools": tools,
    }
    return yaml.dump(config, default_flow_style=False, sort_keys=False, width=120)


# ═══════════════════════════════════════════════════════════════
# Import injection
# ═══════════════════════════════════════════════════════════════

def generate_import_patch(source: str) -> str:
    """Add `from agentmint.notary import Notary` if not already present.

    No visitors, no .walk(), no MetadataWrapper. Just parse → find
    last import index → insert → serialize.
    """
    if "import agentmint" in source or "from agentmint" in source:
        return source

    tree = cst.parse_module(source)

    last_import_idx = -1
    for i, stmt in enumerate(tree.body):
        if isinstance(stmt, cst.SimpleStatementLine):
            for s in stmt.body:
                if isinstance(s, (cst.Import, cst.ImportFrom)):
                    last_import_idx = i

    new_stmt = cst.parse_statement("from agentmint.notary import Notary\n")
    body = list(tree.body)
    body.insert(last_import_idx + 1 if last_import_idx >= 0 else 0, new_stmt)
    return tree.with_changes(body=body).code


# ═══════════════════════════════════════════════════════════════
# Quickstart script generation
# ═══════════════════════════════════════════════════════════════

def generate_quickstart(candidates: List[ToolCandidate]) -> str:
    """Generate a runnable quickstart.py that produces the first receipt.

    This is the 'aha moment' — developer runs it, sees a signed receipt,
    understands what agentmint does in 10 seconds.
    """
    # Pick the most interesting tool for the demo
    # Prefer: high confidence definition, write/exec/delete over read
    priority = {"exec": 4, "delete": 3, "write": 2, "network": 1, "read": 0, "unknown": 0}
    defs = [c for c in candidates
            if c.boundary == "definition" and c.confidence == "high"
            and not c.symbol.startswith("<")]
    if not defs:
        defs = [c for c in candidates if not c.symbol.startswith("<")]
    if not defs:
        return ""

    defs.sort(key=lambda c: priority.get(c.operation_guess, 0), reverse=True)
    demo_tool = defs[0]

    all_scopes = sorted({c.scope_suggestion for c in candidates
                         if not c.symbol.startswith("<")})
    all_agents = sorted({c.framework for c in candidates})

    return f'''#!/usr/bin/env python3
"""
AgentMint Quickstart — generated by `agentmint init`

Run this to see your first signed receipt:
    python3 quickstart.py

What it does:
    1. Creates a Notary (generates an Ed25519 keypair)
    2. Creates a plan with scopes from your scan results
    3. Notarises a simulated tool call
    4. Verifies the receipt signature
    5. Exports an evidence package you can hand to an auditor
"""
from pathlib import Path
from agentmint.notary import Notary

notary = Notary()

# Plan — scopes match your actual tool calls from the scan
plan = notary.create_plan(
    user="developer@yourcompany.com",
    action="agent-ops",
    scope={all_scopes},
    delegates_to=["agent"],
)

# Simulate a tool call — replace with your real tool
receipt = notary.notarise(
    action="{demo_tool.scope_suggestion}",
    agent="agent",
    plan=plan,
    evidence={{
        "tool": "{demo_tool.symbol}",
        "file": "{demo_tool.file}",
        "simulated": True,
    }},
)

# Verify
assert notary.verify_receipt(receipt), "Receipt verification failed!"

print(f"""
✓ Receipt {{receipt.short_id}} — signed and verified

  action:    {demo_tool.scope_suggestion}
  agent:     agent
  in_policy: {{receipt.in_policy}}
  signature: {{receipt.signature[:40]}}...

Next steps:
  1. Add notary.notarise() calls to your real tools (see agentmint init output)
  2. Run `agentmint verify .` in CI to enforce coverage
  3. Export evidence: notary.export_evidence(Path("./evidence"))
""")

# Export evidence package
evidence_dir = Path("./agentmint-evidence")
evidence_dir.mkdir(exist_ok=True)
notary.export_evidence(evidence_dir)
print(f"✓ Evidence exported to {{evidence_dir}}/")
print(f"  Verify independently: cd {{evidence_dir}} && bash verify.sh")
'''


# ═══════════════════════════════════════════════════════════════
# Shield dry-run report
# ═══════════════════════════════════════════════════════════════

def generate_shield_check(candidates: List[ToolCandidate]) -> str:
    """Generate a one-liner shield check the developer can paste.

    Shows what Shield would catch if it were running on their tool inputs.
    """
    tools = [c for c in candidates
             if c.boundary == "definition" and not c.symbol.startswith("<")]
    if not tools:
        return ""

    tool_names = ", ".join(f'"{t.symbol}"' for t in tools[:5])
    return f'''# Dry-run Shield on sample inputs — paste into a Python shell:
from agentmint.shield import scan
result = scan({{"query": "My SSN is 123-45-6789", "tools": [{tool_names}]}})
print(f"Threats: {{result.threat_count}}, Blocked: {{result.blocked}}, Categories: {{result.categories}}")
'''


# ═══════════════════════════════════════════════════════════════
# Patch instructions
# ═══════════════════════════════════════════════════════════════

def _notarise_snippet(scope: str, symbol: str) -> str:
    return (
        f'    # AgentMint: notarise this tool call\n'
        f'    notary.notarise(\n'
        f'        action="{scope}",\n'
        f'        agent="<agent_name>",\n'
        f'        plan=plan,\n'
        f'        evidence={{"tool": "{symbol}"}},\n'
        f'    )\n'
    )


def generate_patch_instructions(candidates: List[ToolCandidate]) -> List[dict]:
    """Generate per-tool patch instructions.

    Returns list of dicts: {file, line, symbol, action, code?, note?}
    """
    instructions = []
    for c in candidates:
        base = {"file": c.file, "line": c.line, "symbol": c.symbol}

        if c.confidence == "low":
            instructions.append({**base, "action": "manual_review",
                                 "note": "Low confidence — review manually"})
        elif c.boundary == "definition":
            action = ("add_notarise_to_run" if c.framework == "crewai" and c.base_classes
                      else "add_notarise_to_body")
            instructions.append({**base, "action": action,
                                 "code": _notarise_snippet(c.scope_suggestion, c.symbol)})
        else:
            instructions.append({**base, "action": "add_to_plan_scope",
                                 "code": f'    "{c.scope_suggestion}",  # {c.symbol}'})

    return instructions
