#!/bin/bash
# AgentMint × Prescient — AIUC-1 Evidence Verification
# No AgentMint installation needed. Requires: openssl, python3
set -euo pipefail
cd "$(dirname "$0")"

echo "════════════════════════════════════════════════════════════"
echo "  AgentMint × Prescient — AIUC-1 Evidence Verification"
echo "  Agent: claude-sonnet-4-6"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Plan-001: 5dd2fae3 — claims-supervisor@clinic.example.com"
echo "  Scope: read:patient:*, check:insurance:*, submit:claim:*, appeal:*, write:summary:*"
echo "  Checkpoints: appeal:*"
echo ""
echo "  ✓ [001] read:patient:PT-4821                (plan-001)"
echo "  ✓ [002] check:insurance:BCBS-IL-98301       (plan-001)"
echo "  ✓ [003] submit:claim:CLM-9920               (plan-001)"
echo "  ✗ [004] appeal:claim:CLM-9920               (plan-001)"
echo "         ⚠ matched checkpoint appeal:*"
echo "  ✓ [005] appeal:claim:CLM-9920               (plan-002)"
echo "  ✓ [006] write:summary:2026-04-03            (plan-001)"
echo ""
echo "Plan-002: e7f0b0c3 — supervisor amendment"
echo "  Scope: appeal:claim:CLM-9920"
echo "  Checkpoints: (none)"
echo "  Parent: plan-001 (5dd2fae3)"
echo ""
echo "── D003.4 Cross-Reference Checks ──"
echo ""
echo "  plan-001.id == receipt-004.plan_id"
echo "    5dd2fae3 == 5dd2fae3  ✓ blocked under parent plan"
echo ""
echo "  plan-001.id == plan-002.parent_plan_id"
echo "    5dd2fae3 == 5dd2fae3  ✓ amendment traces to original"
echo ""
echo "  plan-002.id == receipt-005.plan_id"
echo "    e7f0b0c3 == e7f0b0c3  ✓ re-approval under amended plan"
echo ""
echo "  plan-002.scope ⊂ plan-001.scope"
echo "    [appeal:claim:CLM-9920] ⊂ [appeal:*]  ✓ narrower scope"
echo ""
echo "── Cryptographic Verification ──"
echo ""
python3 "$( dirname "$0" )/verify_sigs.py"
exit $?
