#!/bin/bash
# AgentMint — Healthcare Claims Evidence Verification
# Requires: python3 with pynacl. No AgentMint needed.
set -euo pipefail
cd "$(dirname "$0")"

echo "════════════════════════════════════════════════════════════════"
echo "  AgentMint — Healthcare Claims Evidence Verification"
echo "  Key: c415f398f16ae2e7"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  Plan 001: cf1275ea  user=claims-supervisor@clinic.example.com"
echo "    scope: read:patient:*, check:insurance:*, submit:claim:*, appeal:*, write:summary:*"
echo "    checkpoints: appeal:*"
echo "    delegates: claims-agent"
echo ""
echo "  Plan 002: cd012bcd  user=claims-supervisor@clinic.example.com"
echo "    scope: read:patient:*, check:insurance:*, submit:claim:*, appeal:*, write:summary:*"
echo "    checkpoints: appeal:*"
echo "    delegates: claims-agent-rogue"
echo ""
echo "  Plan 003: a9e88728  user=claims-supervisor@clinic.example.com"
echo "    scope: appeal:claim:CLM-9920"
echo "    checkpoints: appeal:*"
echo "    delegates: appeals-agent"
echo ""
echo "  Plan 004: 18565ea6  user=claims-supervisor@clinic.example.com"
echo "    scope: appeal:claim:CLM-1047"
echo "    checkpoints: appeal:*"
echo "    delegates: appeals-agent"
echo ""
echo "  Plan 005: 2b66e440  user=claims-supervisor@clinic.example.com"
echo "    scope: appeal:claim:CLM-3384"
echo "    checkpoints: appeal:*"
echo "    delegates: appeals-agent"
echo ""
echo "  Plan 006: 5773319c  user=claims-supervisor@clinic.example.com"
echo "    scope: appeal:claim:CLM-5562"
echo "    checkpoints: appeal:*"
echo "    delegates: appeals-agent"
echo ""
echo "  Plan 007: b862688b  user=claims-supervisor@clinic.example.com"
echo "    scope: appeal:claim:CLM-7791"
echo "    checkpoints: appeal:*"
echo "    delegates: appeals-agent"
echo ""
echo "  Plan 008: 0f157bfc  user=claims-supervisor@clinic.example.com"
echo "    scope: appeal:claim:CLM-8823"
echo "    checkpoints: appeal:*"
echo "    delegates: appeals-agent"
echo ""
echo "  ── Delegation Chain ──"
echo ""
echo "    cf1275ea (supervisor)"
echo "      ↳ a9e88728 → appeals-agent  scope: appeal:claim:CLM-9920"
echo "      ↳ 18565ea6 → appeals-agent  scope: appeal:claim:CLM-1047"
echo "      ↳ 2b66e440 → appeals-agent  scope: appeal:claim:CLM-3384"
echo "      ↳ 5773319c → appeals-agent  scope: appeal:claim:CLM-5562"
echo "      ↳ b862688b → appeals-agent  scope: appeal:claim:CLM-7791"
echo "      ↳ 0f157bfc → appeals-agent  scope: appeal:claim:CLM-8823"
echo ""
echo "  ── Chain of Actions ──"
echo ""
echo "  ✓ [001] read:patient:PT-4821                   matched scope read:patient:*"
echo "  ✓ [002] check:insurance:BCBS-IL-98301          matched scope check:insurance:*"
echo "  ✓ [003] submit:claim:CLM-9920                  matched scope submit:claim:*"
echo "  ✗ [004] appeal:claim:CLM-9920                  BLOCKED"
echo "         matched checkpoint appeal:*"
echo "  ✗ [005] appeal:claim:CLM-9920                  BLOCKED  [appeals-agent]"
echo "         matched checkpoint appeal:*"
echo "  ✓ [006] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [007] read:patient:PT-5190                   matched scope read:patient:*"
echo "  ✓ [008] check:insurance:AETNA-TX-44102         matched scope check:insurance:*"
echo "  ✓ [009] submit:claim:CLM-1047                  matched scope submit:claim:*"
echo "  ✗ [010] appeal:claim:CLM-1047                  BLOCKED"
echo "         matched checkpoint appeal:*"
echo "  ✗ [011] appeal:claim:CLM-1047                  BLOCKED  [appeals-agent]"
echo "         matched checkpoint appeal:*"
echo "  ✓ [012] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [013] read:patient:PT-3377                   matched scope read:patient:*"
echo "  ✓ [014] check:insurance:CIGNA-CA-55910         matched scope check:insurance:*"
echo "  ✓ [015] submit:claim:CLM-3384                  matched scope submit:claim:*"
echo "  ✗ [016] appeal:claim:CLM-3384                  BLOCKED"
echo "         matched checkpoint appeal:*"
echo "  ✗ [017] appeal:claim:CLM-3384                  BLOCKED  [appeals-agent]"
echo "         matched checkpoint appeal:*"
echo "  ✓ [018] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [019] read:patient:PT-6201                   matched scope read:patient:*"
echo "  ✓ [020] check:insurance:UHC-NY-82714           matched scope check:insurance:*"
echo "  ✓ [021] submit:claim:CLM-5562                  matched scope submit:claim:*"
echo "  ✗ [022] appeal:claim:CLM-5562                  BLOCKED"
echo "         matched checkpoint appeal:*"
echo "  ✗ [023] appeal:claim:CLM-5562                  BLOCKED  [appeals-agent]"
echo "         matched checkpoint appeal:*"
echo "  ✓ [024] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [025] read:patient:PT-7045                   matched scope read:patient:*"
echo "  ✓ [026] check:insurance:HUMANA-FL-33021        matched scope check:insurance:*"
echo "  ✓ [027] submit:claim:CLM-7791                  matched scope submit:claim:*"
echo "  ✗ [028] appeal:claim:CLM-7791                  BLOCKED"
echo "         matched checkpoint appeal:*"
echo "  ✗ [029] appeal:claim:CLM-7791                  BLOCKED  [appeals-agent]"
echo "         matched checkpoint appeal:*"
echo "  ✓ [030] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [031] read:patient:PT-4498                   matched scope read:patient:*"
echo "  ✓ [032] check:insurance:KAISER-OR-60145        matched scope check:insurance:*"
echo "  ✓ [033] submit:claim:CLM-8823                  matched scope submit:claim:*"
echo "  ✗ [034] appeal:claim:CLM-8823                  BLOCKED"
echo "         matched checkpoint appeal:*"
echo "  ✗ [035] appeal:claim:CLM-8823                  BLOCKED  [appeals-agent]"
echo "         matched checkpoint appeal:*"
echo "  ✓ [036] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [037] read:patient:PT-2916                   matched scope read:patient:*"
echo "  ✓ [038] check:insurance:ANTHEM-VA-19832        matched scope check:insurance:*"
echo "  ✓ [039] submit:claim:CLM-4410                  matched scope submit:claim:*"
echo "  ✓ [040] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [041] read:patient:PT-8107                   matched scope read:patient:*"
echo "  ✓ [042] check:insurance:BCBS-GA-37291          matched scope check:insurance:*"
echo "  ✓ [043] submit:claim:CLM-6105                  matched scope submit:claim:*"
echo "  ✓ [044] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [045] read:patient:PT-1683                   matched scope read:patient:*"
echo "  ✓ [046] check:insurance:MOLINA-AZ-48503        matched scope check:insurance:*"
echo "  ✓ [047] submit:claim:CLM-9238                  matched scope submit:claim:*"
echo "  ✓ [048] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [049] read:patient:PT-8834                   matched scope read:patient:*"
echo "  ✓ [050] check:insurance:UHC-WA-71920           matched scope check:insurance:*"
echo "  ✓ [051] submit:claim:CLM-2847                  matched scope submit:claim:*"
echo "  ✓ [052] write:summary:batch-2026-04            matched scope write:summary:*"
echo "  ✓ [053] read:patient:PT-4821                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [054] shield:scraped_record:PT-4821          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [055] read:patient:PT-4498                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [056] auto-deny:claim:CLM-9920               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [057] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [058] check:insurance:BCBS-IL-98301          matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [059] submit:claim:CLM-9920                  matched scope submit:claim:*  [claims-agent-rogue]"
echo "  ✓ [060] read:patient:PT-5190                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [061] shield:scraped_record:PT-5190          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [062] read:patient:PT-2916                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [063] auto-deny:claim:CLM-1047               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [064] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [065] check:insurance:AETNA-TX-44102         matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [066] submit:claim:CLM-1047                  matched scope submit:claim:*  [claims-agent-rogue]"
echo "  ✓ [067] read:patient:PT-3377                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [068] shield:scraped_record:PT-3377          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [069] read:patient:PT-8107                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [070] auto-deny:claim:CLM-3384               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [071] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [072] check:insurance:CIGNA-CA-55910         matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [073] submit:claim:CLM-3384                  matched scope submit:claim:*  [claims-agent-rogue]"
echo "  ✓ [074] read:patient:PT-6201                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [075] shield:scraped_record:PT-6201          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [076] read:patient:PT-1683                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [077] auto-deny:claim:CLM-5562               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [078] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [079] check:insurance:UHC-NY-82714           matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [080] submit:claim:CLM-5562                  matched scope submit:claim:*  [claims-agent-rogue]"
echo "  ✓ [081] read:patient:PT-7045                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [082] shield:scraped_record:PT-7045          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [083] read:patient:PT-8834                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [084] auto-deny:claim:CLM-7791               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [085] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [086] check:insurance:HUMANA-FL-33021        matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [087] submit:claim:CLM-7791                  matched scope submit:claim:*  [claims-agent-rogue]"
echo "  ✓ [088] read:patient:PT-4498                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [089] shield:scraped_record:PT-4498          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [090] read:patient:PT-4821                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [091] auto-deny:claim:CLM-8823               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [092] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [093] check:insurance:KAISER-OR-60145        matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [094] submit:claim:CLM-8823                  matched scope submit:claim:*  [claims-agent-rogue]"
echo "  ✓ [095] read:patient:PT-2916                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [096] shield:scraped_record:PT-2916          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [097] read:patient:PT-5190                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [098] auto-deny:claim:CLM-4410               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [099] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [100] check:insurance:ANTHEM-VA-19832        matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [101] submit:claim:CLM-4410                  matched scope submit:claim:*  [claims-agent-rogue]"
echo "  ✓ [102] read:patient:PT-8107                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [103] shield:scraped_record:PT-8107          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [104] read:patient:PT-3377                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [105] auto-deny:claim:CLM-6105               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [106] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [107] check:insurance:BCBS-GA-37291          matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [108] submit:claim:CLM-6105                  matched scope submit:claim:*  [claims-agent-rogue]"
echo "  ✓ [109] read:patient:PT-1683                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [110] shield:scraped_record:PT-1683          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [111] read:patient:PT-6201                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [112] auto-deny:claim:CLM-9238               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [113] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [114] check:insurance:MOLINA-AZ-48503        matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [115] submit:claim:CLM-9238                  matched scope submit:claim:*  [claims-agent-rogue]"
echo "  ✓ [116] read:patient:PT-8834                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [117] shield:scraped_record:PT-8834          BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [118] read:patient:PT-7045                   matched scope read:patient:*  [claims-agent-rogue]"
echo "  ✗ [119] auto-deny:claim:CLM-2847               BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✗ [120] export:all-patients                    BLOCKED  [claims-agent-rogue]"
echo "         no scope pattern matched"
echo "  ✓ [121] check:insurance:UHC-WA-71920           matched scope check:insurance:*  [claims-agent-rogue]"
echo "  ✓ [122] submit:claim:CLM-2847                  matched scope submit:claim:*  [claims-agent-rogue]"
echo ""
echo "  ── Cryptographic Verification ──"
echo ""
python3 "$(dirname "$0")/verify_sigs.py"
EXIT=$?
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  Verified with: openssl + python3"
echo "  No AgentMint installation required."
echo "════════════════════════════════════════════════════════════════"
exit $EXIT
